### ISSUE TITLE
In Collaborative filtering for 'implicit feedback' data          I ran your code produced a TypeError: invalid type comparison  

### ISSUE THREAD

**Issue by superrui0810** [david-cortes/datascienceprojects#1]
TypeError                                 Traceback (most recent call last)
<ipython-input-5-9f5f883fa1c7> in <module>()
     13 
     14 
---> 15     xhat=theano.tensor.sum(theta[train.UserId] * beta[train.artist], axis=1)
     16 
     17     R=pm.Poisson('R',mu=xhat, observed=train.Playcount.astype('float32'))

D:\Anaconda3-5\lib\site-packages\theano\tensor\var.py in __getitem__(self, args)
    505         # Else leave it as is if it is a real number
    506         args = tuple([numpy.array(inp, dtype=numpy.int64)
--> 507                       if(inp == [] or inp == ()) else inp for inp in args])
    508         # Convert python literals to theano constants
    509         args = theano.tensor.subtensor.make_constant(args)

D:\Anaconda3-5\lib\site-packages\theano\tensor\var.py in <listcomp>(.0)
    505         # Else leave it as is if it is a real number
    506         args = tuple([numpy.array(inp, dtype=numpy.int64)
--> 507                       if(inp == [] or inp == ()) else inp for inp in args])
    508         # Convert python literals to theano constants
    509         args = theano.tensor.subtensor.make_constant(args)

D:\Anaconda3-5\lib\site-packages\pandas\core\ops.py in wrapper(self, other, axis)
    859 
    860             with np.errstate(all='ignore'):
--> 861                 res = na_op(values, other)
    862             if is_scalar(res):
    863                 raise TypeError('Could not compare %s type with Series' %

D:\Anaconda3-5\lib\site-packages\pandas\core\ops.py in na_op(x, y)
    798                     result = getattr(x, name)(y)
    799                 if result is NotImplemented:
--> 800                     raise TypeError("invalid type comparison")
    801             except AttributeError:
    802                 result = op(x, y)

TypeError: invalid type comparison

**Comment by superrui0810** [comment]
my pymc3 version 3.2     pandas version  2.0

**Comment by david-cortes** [comment]
Just tried it under an old theano version and got the same error. Are you using theano 1.0.1?

**Comment by superrui0810** [comment]
My theano version is0.9

**Comment by david-cortes** [comment]
Sorry, no idea how to make it work under older theano versions. Guess you’ll have to update (theano 1.0.1 is available on pip).

If you still cannot get it to work, you might want to try the author’s implementation (which is not python):
https://github.com/premgopalan/hgaprec

**Comment by superrui0810** [comment]
I have updated my theano to 1.0.1 and it did work  Thanks a lot
